service: auth-service

provider:
  name: aws
  runtime: nodejs10.x
  # These environment variables are made available to our functions
  # under process.env.
  environment:
    tableName: ${self:custom.tableName}
    # this is the only thing that can't be done via Cloudformation yet, either we need an script, or manually, add it to the Parameter Store
    COGNITO_POOL_USER_ID: ${ssm:cognitoPoolUserId~true}
    COGNITO_USER_CLIENT_ID: ${ssm:cognitoUserClientId~true}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      # Restrict our IAM role permissions to
      # the specific table for the stage
      Resource:
        - "Fn::GetAtt": [ UsersTable, Arn ]


plugins:
  - serverless-offline
  - serverless-plugin-warmup
  - serverless-dynamodb-local
  - serverless-pseudo-parameters
  - serverless-ignore

custom:
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
    migration:
      dir: offline/migrations
  # Our stage is based on what is passed in when running serverless
  # commands. Or fallback to what we have set in the provider section.
  stage: ${opt:stage, self:provider.stage}
  # Set the table name here so we can use it while testing locally
  tableName: ${self:custom.stage}-users


functions:
  signup:
    handler: src/api/users.signUp
    events:
      - http:
          path: signup/
          method: post
          integration: lambda
          cors: true
  auth:
    handler: authorizer.authorize
  privateEndpoint:
    handler: src/api/users.privateEndpoint
    events:
      - http:
          path: api/private
          method: get
          authorizer: auth
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - Authorization


resources:
  # DynamoDB
  - ${file(resources/dynamo-table.yml)}
  # Cognito
  - ${file(resources/cognito-user-pool.yml)}
  - ${file(resources/cognito-identity-pool.yml)}


